global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["<DROPLET_IP>:9100"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["<DROPLET_IP>:9187"]
